### ISSUE TITLE
how to add the change-password page

### ISSUE THREAD

**Issue by peoplea** [baijiacms/baijiacmsV2#2]
how to add the change-password page,i can't to add it

**Comment by baijiacms** [comment]
refer to system function or wiki
https://github.com/baijiacms/baijiacms/wiki/%E4%BA%8C%E6%AC%A1%E5%BC%80%E5%8F%91:%E6%8F%92%E4%BB%B6%E6%A8%A1%E5%9D%97%E5%BC%80%E5%8F%91%E6%8C%87%E5%8D%97
